apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: tags-to-tables
spec:
  schedule: "0 1 * * 6"
  timezone: "Europe/Moscow"
  workflowSpec:
    workflowTemplateRef:
      name: tags-to-tables
